server:
  port: 8891
spring:
  #h2:
    #console:
      #enabled: true
      #path: /h2-console
  datasource:
    driver-class-name: org.postgresql.Driver
    #driver-class-name: org.h2.Driver
    #url: postgres://ocnohfpvcmegfx:26a8fe38f4be31f8e2b9048b0baf47d1674d3582d6e9e7f5b3c7b14690202b9c@ec2-35-168-122-84.compute-1.amazonaws.com:5432/dbef637bg854d9
    url: jdbc:postgresql://sa-east-1.2945b742-34f8-4514-92bd-ff2acd7cedf0.aws.ybdb.io:5433/yugabyte
    #url: jdbc:h2:file:~/data/clientDB;
    #postgres://ocnohfpvcmegfx:26a8fe38f4be31f8e2b9048b0baf47d1674d3582d6e9e7f5b3c7b14690202b9c@ec2-35-168-122-84.compute-1.amazonaws.com:5432/dbef637bg854d9
    #jdbc:h2:file:~/data/clientDB;
    #username: ocnohfpvcmegfx
    #username: sa
    #password: admin
    username: admin
    password: pdhS4ypNQtmMNvtcC6mvyKqd5jd7HK
    #postgres
    #ocnohfpvcmegfx
    #sa
    #password: 26a8fe38f4be31f8e2b9048b0baf47d1674d3582d6e9e7f5b3c7b14690202b9c
    #password
    #26a8fe38f4be31f8e2b9048b0baf47d1674d3582d6e9e7f5b3c7b14690202b9c
    #admin
  jpa:
    database: postgresql
    #database: h2
    #h2
    hibernate:
      ddl-auto: update
    show_sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
    #org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha